config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'

   resources :users

   get '/login', to: 'users#login', as: 'login_page'
   post '/login', to: 'users#new_session', as: 'login'
   delete '/logout', to: 'users#logout', as: 'logout'
 end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :format
  has_many   :listening_sessions
end

app/models/format.rb
class Format < ActiveRecord::Base
  has_many :albums
end

app/models/listening_session.rb
class ListeningSession < ActiveRecord::Base
  belongs_to :user
  belongs_to :album
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :listening_sessions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  protect_from_forgery
  
  def new
    @user = User.new
    render template: "users/new"
  end

  def login
    if current_user
      redirect_to "/users/#{current_user.id}"
    else
      render template: "users/login"
    end
  end

  def new_session
    @user = User.find_by(email: user_params[:email])
    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      redirect_to "/users/#{current_user.id}"
    else
    end
  end

  def create
    if !current_user
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to "/users/#{current_user.id}"
      else
        render template: 'users/new'
      end
    end
  end

  def logout
    session.delete(:user_id)
    redirect_to "/"
  end

  def show
    if current_user.id.to_s == params[:id]
      render template: 'users/show'
    else
      redirect_to login_page_path 
    end
  end


  private
  def current_user
    if session[:user_id] == nil
      nil
    else
      User.find(session[:user_id])
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :username)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render template: "welcome"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user
    return nil if session[:user_id].nil?
    User.find(session[:user_id])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SongJournal</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user -%>
    <li><%= link_to 'logout', logout_path, method: :delete %></li>
  <% else %>
    <li><%= link_to 'login', login_page_path %></li>
    <li><%= link_to 'create account', new_user_path %></li>
  <% end %>  
<%= yield %>

</body>
</html>

app/views/users/_login_form.html.erb
<%= form_for :user, url: login_path do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit 'submit' %>
<% end %> 

app/views/users/_reg_form.html.erb
<%= form_for @user do |f| %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit 'submit' %>
<% end %> 

app/views/users/login.html.erb
<h4>Please enter your information:</h4>

<%= render 'login_form' %>

app/views/users/new.html.erb
<h4>Sign up for an account</h4>

<%= render 'reg_form'%>

app/views/users/show.html.erb
<h2> Hi <%=current_user.first_name%>! </h2>
<h4> What are you listening to? </h4>